version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        REQUIREMENTS_FILE: dev.txt
    environment:
      - LOG_TYPE=console
      - LOG_LEVEL=info
      - PG_DSN=postgresql://postgres:mysecretpassword@db:5432/postgres
    command: [ "test", "--wait-for-db", "postgresql://postgres:mysecretpassword@db:5432/postgres" ]
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_PASSWORD=mysecretpassword