version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        REQUIREMENTS_FILE: dev.txt
    volumes:
      - .:/app
    command: [ "test" ]
  db:
    image: postgres:13.0
    env_file:
      - .env
