version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        REQUIREMENTS_FILE: dev.txt
    environment:
      - LOG_TYPE=console
      - LOG_LEVEL=info
      - PG_DSN=postgres://user:pass@localhost:5432/foobar
    command: [ "lint" ]
